# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8aa2d25058c8d759add1566569ca741b5565362578059c8be2c5352b80ef49b77fd4240c4670e69d3140071e20d0f0192603730ffacdb62c7e166cf048773e75

test:
  secret_key_base: fbce3bb6126bdfbf2b69b0317331b09e7954b7ef790c7c82669ceda8348e82a1f76aa700ac1d282f86f483cd2ad1e81daa2c6a71427bd0d2236aa8a972d0cc50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
